TE-9607 Covered code with tests
yaroslav-spryker/integrator pull request #1
Opened 2021-09-08 14:02 UTC by geega

2021-09-14 10:59 UTC, gechetspr requested changes
Looks good, but there are a few things to fix.

Also a lot of ToDos in the code

2021-09-14 10:59 UTC, gechetspr commented on src/SprykerSdk/Integrator/Business/Manifest/ManifestReader.php
> +        var_dump($recipesArchive);
leftovers

2021-09-14 10:59 UTC, gechetspr commented on src/SprykerSdk/Integrator/Business/ManifestStrategy/CopyModuleFileManifestStrategy.php
> +            . strtolower($this->camelCaseToDash($organisation))
it's always good idea to use mb_* functions

2021-09-14 10:59 UTC, gechetspr commented on src/SprykerSdk/Shared/Common/AbstractConfig.php
> +     * @api
no need for api tags for a library

2021-09-14 10:59 UTC, gechetspr commented on src/SprykerSdk/Shared/ModuleFinder/ModuleFinderFactoryAwareTrait.php
> +declare(strict_types = 1);
it's without spaces in official docs

2021-09-14 10:59 UTC, gechetspr commented on tests/bootstrap.php
> +<?php
why do we need this file?

2021-09-16 07:01 UTC, geega commented on tests/bootstrap.php
> +<?php
To define constants for run PHPUnit only.

2021-09-16 07:05 UTC, merged